ROS 2 dockerized example for nmea GPS
husarion/nmea-gps-docker pull request #3
Opened 2024-02-12 11:18 UTC by delihus

Created ros2 workflow with standard date and package version tag.
Moved `compose.yaml` to `demo/` folder.

2024-02-13 13:07 UTC, pkowalsk1 requested changes

2024-02-13 13:07 UTC, pkowalsk1 commented on Dockerfile
> +## =========================== ROS builder ===============================
[major]
What's the purpose of having a separate entity building the package? The same packages are installed in both stages (i.e., ros-dev-tools), and rosdep is called twice with the same dependencies. In my opinion, this only complicates and unnecessarily prolongs the build process. I suggest installing and building everything sequentially in a single RUN command.

2024-02-13 13:07 UTC, pkowalsk1 commented on Dockerfile
> +    rosdep init && \
Is it really necessary? If certain dependencies are already included in the husarnet/ros image, I believe they should be installed directly. Moreover, could you elaborate on the advantages and disadvantages of using this particular image? What rationale led us to choose it for this relatively straightforward use case over the basic ros docker image?

2024-02-13 13:07 UTC, pkowalsk1 commented on Dockerfile
> +    rm -rf src && \
I understand the importance of minimizing the image size, but in my opinion, this step may not be necessary. What do you think?

2024-02-13 13:07 UTC, pkowalsk1 commented on README.md
> +</h1>
```suggestion
# Docker Images for a GPS module
```
Alternatively, even the `# nmea-gps-docker`

2024-02-13 13:07 UTC, pkowalsk1 commented on README.md
> +### GPS API
Can we align this ROS API and the whole README with our standards, like [here](https://hedgedoc.internal.husarion.com/readme-wrtiting) or [here]( https://github.com/husarion/panther_ros/tree/ros1/panther_driver#ros-nodes)?

2024-02-13 13:07 UTC, pkowalsk1 commented on .github/workflows/build-docker-image.yaml
> +        default: development
By the way, is it still in development or stable? I think we should aim to stabilize it and move away from reliance on this image. Are there plans to release tag v1.0.0 or something similar?

2024-02-14 08:15 UTC, delihus commented on Dockerfile
> +## =========================== ROS builder ===============================
There are some differences between `ros-core` and `ros-base` image but I can try to move this to one stage.

2024-02-14 08:23 UTC, delihus commented on Dockerfile
> +    rosdep init && \
Removing the sources is not necessary but rosdep has to be initialized other way it gives:
![image](https://github.com/husarion/nmea-gps-docker/assets/109142865/239636cc-abed-49a5-9a13-4a217eed14a0)

2024-02-14 08:24 UTC, delihus commented on Dockerfile
> +    rm -rf src && \
I think it is good practice to reduce the image size as much as possible.

2024-02-14 08:38 UTC, delihus commented on .github/workflows/build-docker-image.yaml
> +        default: development
In the docker repositories we added the development and the release build. Here are the options:
![image](https://github.com/husarion/nmea-gps-docker/assets/109142865/fffcd110-5ba1-4071-9ef4-ff95353cf1f6)

The purpose is to push images with date and package version.
![image](https://github.com/husarion/nmea-gps-docker/assets/109142865/5beed130-d6f9-42ef-8dc3-e2e6766f0405)

After the PR is closed we can trigger the release build to make sure that image is tested and does work.
![image](https://github.com/husarion/nmea-gps-docker/assets/109142865/e772499a-97f0-48bd-b87a-cb90702b5669)
It adds to existing image e. g. `humble-2.0.1-20240209` `-stable` to the tag what gives `humble-2.0.1-20240209-stable`.

Referring to the version. The tag of images are versions of the built package described in `package.xml` and the date of docker image build.

2024-02-14 12:37 UTC, pkowalsk1 commented on .github/workflows/build-docker-image.yaml
> +        default: development
I apologize for the misunderstanding. I've used this feature before, but I was referring to the GitHub tag.

2024-02-15 12:50 UTC, delihus commented on .github/workflows/build-docker-image.yaml
> +        default: development
okay! So after the PR I can release this!

2024-02-16 10:10 UTC, pkowalsk1 approved these changes

2024-02-16 10:10 UTC, merged